<a href="https://colab.research.google.com/github/tatianaportsova/-Life-Expectancy.-USA-Project/blob/master/Copy_of_LS_DS_214_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lambda School Data Science

*Unit 2, Sprint 1, Module 4*

---

# Logistic Regression


## Assignment 🌯

You'll use a [**dataset of 400+ burrito reviews**](https://srcole.github.io/100burritos/). How accurately can you predict whether a burrito is rated 'Great'?

> We have developed a 10-dimensional system for rating the burritos in San Diego. ... Generate models for what makes a burrito great and investigate correlations in its dimensions.

- [ ] Do train/validate/test split. Train on reviews from 2016 & earlier. Validate on 2017. Test on 2018 & later.
- [ ] Begin with baselines for classification.
- [ ] Use scikit-learn for logistic regression.
- [ ] Get your model's validation accuracy. (Multiple times if you try multiple iterations.)
- [ ] Get your model's test accuracy. (One time, at the end.)
- [ ] Commit your notebook to your fork of the GitHub repo.


## Stretch Goals

- [ ] Add your own stretch goal(s) !
- [ ] Make exploratory visualizations.
- [ ] Do one-hot encoding.
- [ ] Do [feature scaling](https://scikit-learn.org/stable/modules/preprocessing.html).
- [ ] Get and plot your coefficients.
- [ ] Try [scikit-learn pipelines](https://scikit-learn.org/stable/modules/compose.html).

In [0]:
%%capture
import sys

# If you're on Colab:
if 'google.colab' in sys.modules:
    DATA_PATH = 'https://raw.githubusercontent.com/LambdaSchool/DS-Unit-2-Linear-Models/master/data/'
    !pip install category_encoders==2.*

# If you're working locally:
else:
    DATA_PATH = '../data/'

In [0]:
# Load data downloaded from https://srcole.github.io/100burritos/
import pandas as pd
df = pd.read_csv(DATA_PATH+'burritos/burritos.csv')

In [0]:
# Derive binary classification target:
# We define a 'Great' burrito as having an
# overall rating of 4 or higher, on a 5 point scale.
# Drop unrated burritos.
df = df.dropna(subset=['overall'])
df['Great'] = df['overall'] >= 4

In [0]:
# Clean/combine the Burrito categories
df['Burrito'] = df['Burrito'].str.lower()

california = df['Burrito'].str.contains('california')
asada = df['Burrito'].str.contains('asada')
surf = df['Burrito'].str.contains('surf')
carnitas = df['Burrito'].str.contains('carnitas')

df.loc[california, 'Burrito'] = 'California'
df.loc[asada, 'Burrito'] = 'Asada'
df.loc[surf, 'Burrito'] = 'Surf & Turf'
df.loc[carnitas, 'Burrito'] = 'Carnitas'
df.loc[~california & ~asada & ~surf & ~carnitas, 'Burrito'] = 'Other'

In [0]:
# Drop some high cardinality categoricals
df = df.drop(columns=['Notes', 'Location', 'Reviewer', 'Address', 'URL', 'Neighborhood'])

In [0]:
# Drop some columns to prevent "leakage"
df = df.drop(columns=['Rec', 'overall'])

In [273]:
print(df.shape)
df.head()

(421, 59)


Burrito       Date  Yelp  Google Chips  ...  Sushi  Avocado  Corn  Zucchini  Great
0  California  1/18/2016   3.5     4.2   NaN  ...    NaN      NaN   NaN       NaN  False
1  California  1/24/2016   3.5     3.3   NaN  ...    NaN      NaN   NaN       NaN  False
2    Carnitas  1/24/2016   NaN     NaN   NaN  ...    NaN      NaN   NaN       NaN  False
3       Asada  1/24/2016   NaN     NaN   NaN  ...    NaN      NaN   NaN       NaN  False
4  California  1/27/2016   4.0     3.8     x  ...    NaN      NaN   NaN       NaN   True

[5 rows x 59 columns]

### Do train/validate/test split. Train on reviews from 2016 & earlier. Validate on 2017. Test on 2018 & later.


In [0]:
df['Date'] = pd.to_datetime(df['Date'], infer_datetime_format = True) 

In [275]:
# Split the data into train, val, test dataframes
train = df[df['Date'] < '2017-01-01']
val = df[(df['Date'] >= '2017-01-01') & (df['Date'] < '2018-01-01')]
test = df[df['Date'] >= '2018-01-01']
print(train.shape)
print(val.shape)
print(test.shape)

(298, 59)
(85, 59)
(38, 59)


### Begin with baselines for classification.


In [276]:
target = 'Great'
y_train = train[target]
y_train.value_counts(normalize=True)

False    0.590604
True     0.409396
Name: Great, dtype: float64

In [0]:
# Just for demonstration
majority_class = y_train.mode()[0]
y_pred = [majority_class] * len(y_train)

In [278]:
from sklearn.metrics import accuracy_score

# Training accuracy of majority class baseline = 
# frequency of majority class (aka base rate)
accuracy_score(y_train, y_pred)

0.5906040268456376

In [279]:
# Validation accuracy of majority class baseline = 
# usually similar to Train accuracy
y_val = val[target]
y_pred = [majority_class] * len(y_val)
accuracy_score(y_val, y_pred)

0.5529411764705883

### Use scikit-learn for logistic regression.


In [280]:
df.columns

Index(['Burrito', 'Date', 'Yelp', 'Google', 'Chips', 'Cost', 'Hunger',
       'Mass (g)', 'Density (g/mL)', 'Length', 'Circum', 'Volume', 'Tortilla',
       'Temp', 'Meat', 'Fillings', 'Meat:filling', 'Uniformity', 'Salsa',
       'Synergy', 'Wrap', 'Unreliable', 'NonSD', 'Beef', 'Pico', 'Guac',
       'Cheese', 'Fries', 'Sour cream', 'Pork', 'Chicken', 'Shrimp', 'Fish',
       'Rice', 'Beans', 'Lettuce', 'Tomato', 'Bell peper', 'Carrots',
       'Cabbage', 'Sauce', 'Salsa.1', 'Cilantro', 'Onion', 'Taquito',
       'Pineapple', 'Ham', 'Chile relleno', 'Nopales', 'Lobster', 'Queso',
       'Egg', 'Mushroom', 'Bacon', 'Sushi', 'Avocado', 'Corn', 'Zucchini',
       'Great'],
      dtype='object')

In [281]:
# Arrange X feature matrices (already did y target vectors)
features = ['Burrito', 'Yelp', 'Google', 'Chips', 'Cost', 'Hunger',
       'Mass (g)', 'Density (g/mL)', 'Length', 'Circum', 'Volume', 'Tortilla',
       'Temp', 'Meat', 'Fillings', 'Meat:filling', 'Uniformity', 'Salsa',
       'Synergy', 'Wrap', 'Unreliable', 'NonSD', 'Beef', 'Pico', 'Guac',
       'Cheese', 'Fries', 'Sour cream', 'Pork', 'Chicken', 'Shrimp', 'Fish',
       'Rice', 'Beans', 'Lettuce', 'Tomato', 'Bell peper', 'Carrots',
       'Cabbage', 'Sauce', 'Salsa.1', 'Cilantro', 'Onion', 'Taquito',
       'Pineapple', 'Ham', 'Chile relleno', 'Nopales', 'Lobster', 'Queso',
       'Egg', 'Mushroom', 'Bacon', 'Sushi', 'Avocado', 'Corn', 'Zucchini']
target = 'Great'

X_train = train[features]
y_train = train[target]
X_val = val[features]
y_val = val[target]

X_train.shape, y_train.shape, X_val.shape, y_val.shape

((298, 57), (298,), (85, 57), (85,))

In [282]:
import category_encoders as ce
encoder = ce.OneHotEncoder(use_cat_names = True)
X_train_encode = encoder.fit_transform(X_train)
print(X_train_encode.shape)
X_train_encode.head(2)

(298, 123)


Burrito_California  Burrito_Carnitas  ...  Zucchini_nan  Zucchini_x
0                   1                 0  ...             1           0
1                   1                 0  ...             1           0

[2 rows x 123 columns]

In [283]:
X_val_encode = encoder.transform(X_val)
print(X_val_encode.shape)
X_val_encode.head(2)

(85, 123)


Burrito_California  Burrito_Carnitas  ...  Zucchini_nan  Zucchini_x
301                   1                 0  ...             1           0
302                   0                 0  ...             1           0

[2 rows x 123 columns]

In [0]:
# Impute missing values
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')
X_train_imputed = imputer.fit_transform(X_train_encode)
X_val_imputed = imputer.transform(X_val_encode)

In [0]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_imputed)
X_val_scaled = scaler.transform(X_val_imputed)

In [0]:
import warnings
warnings.simplefilter('ignore')

In [287]:
from sklearn.linear_model import LogisticRegressionCV

model = LogisticRegressionCV()
model.fit(X_train_scaled, y_train)

LogisticRegressionCV(Cs=10, class_weight=None, cv=None, dual=False,
                     fit_intercept=True, intercept_scaling=1.0, l1_ratios=None,
                     max_iter=100, multi_class='auto', n_jobs=None,
                     penalty='l2', random_state=None, refit=True, scoring=None,
                     solver='lbfgs', tol=0.0001, verbose=0)

### Get your model's validation accuracy. (Multiple times if you try multiple iterations.)


In [288]:
print('Validation Accuracy', model.score(X_val_scaled, y_val))

Validation Accuracy 0.7647058823529411


In [289]:
X_train_encode.shape

(298, 123)

In [293]:
%matplotlib inline
coefficients = pd.Series(model.coef_[0], X_train_encode.columns)
coefficients.sort_values().plot.barh();

ValueError: ignored

### Get your model's test accuracy. (One time, at the end.)


In [0]:
import numpy as np

In [0]:
test_case = test_case[~np.isnan(test_case)]

In [0]:
test_case = [[1.  , 0.  , 0.  , 0.  , 0.  , 1.  , 1.  , 0.  , 0.  , 6.25, 3.  , 4.  ,
        2.  , 2.  , 4.  , 4.  , 3.  , 4.  , 1.  , 0.  , 1.  , 0.  , 0.  ,
        1.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 1.  , 0.  , 1.  , 1.  , 0.  ,
        0.  , 1.  , 0.  , 0.  , 1.  , 0.  , 0.  , 1.  , 0.  , 0.  , 1.  ,
        0.  , 0.  , 1.  , 0.  , 1.  , 0.  , 1.  , 0.  , 0.  , 1.  , 0.  , 0.  ,
        1.  , 0.  , 0.  , 1.  , 0.  , 0.  , 1.  , 1.  , 0.  , 0.  , 1.  , 0.  ,
        0.  , 1.  , 0.  , 1.  , 0.  , 0.  , 1.  , 0.  , 0.  , 1.  , 0.  ,
        0.  , 1.  , 0.  , 0.  , 1.  , 0.  , 0.  , 1.  , 0.  , 0.  , 1.  ,
        0.  , 0.  , 1.  , 0.  , 1.  , 0.  , 1.  , 0.  , 1.  , 0.  , 1.  ,
        0.  , 1.  , 0.  , 1.  , 1.  , 0.  , 1.  , 1.  , 1.  , 0.  , 1.  , 0.  , 1.  , 0.  ,
        0.  , 1.  , 0.  ]]

In [259]:
log_reg.predict(test_case)

array([False])

In [260]:
log_reg.predict_proba(test_case)

array([[0.92044268, 0.07955732]])

In [261]:
# What's the math?
log_reg.coef_[0]

array([ 5.08340792e-01, -6.11813511e-01, -1.64409106e-01, -4.39744169e-01,
        3.42136906e-01, -5.23230410e-01, -1.12125058e+00, -4.49327614e-01,
        1.56226219e-01, -7.23876936e-02,  1.17048295e-01,  1.29873956e-01,
        5.96821603e-02, -2.21633097e-01,  5.29911102e-01,  5.89349929e-01,
        4.53332300e-01,  1.37597996e+00,  1.05808292e+00,  1.42544783e+00,
       -1.29106206e-01,  1.10731954e-01,  1.61064319e+00,  7.68878942e-04,
       -5.95384188e-01,  2.29895100e-01, -9.95619856e-02, -2.79928411e-01,
        1.40013082e-02, -3.60945808e-01, -2.80163838e-01,  2.75620557e-01,
        2.63750182e-01, -3.09310448e-01, -3.19928823e-01, -3.07763576e-01,
       -2.09468737e-01,  1.51743225e-01,  5.13750990e-02, -2.95203928e-01,
       -1.21660260e-01, -2.48293725e-01,  6.48702938e-02, -1.82065657e-01,
       -1.35437943e-01, -4.10356536e-01,  1.80305390e-01, -4.58735681e-01,
        4.19463447e-02,  5.13002483e-02,  1.53099797e-01, -1.46418092e-01,
       -3.72170793e-01,  

In [262]:
log_reg.intercept_

array([-7.94408495])